---
pip:
  - git+https://github.com/DigitalSlideArchive/girder_volview
  - git+https://github.com/girder/girder-volview-dicomrt
  - git+https://github.com/BryonLewis/dive-dsa.git#subdirectory=server
  - git+https://github.com/DigitalSlideArchive/girder-clamav
# both girder-dicom-viewer and girder-xtk-demo can be used to view radiology
# data, but volview does a better job.  girder-archive-access extends
# girder-dicom-viewer to let it read zip files
shell:
  - pip uninstall -y girder-dicom-viewer girder-xtk-demo girder-archive-access
rebuild-client: True
settings:
  worker.broker: "amqp://guest:guest@rabbitmq"
  worker.backend: "rpc://guest:guest@rabbitmq"
  worker.api_url: "http://girder:8080/api/v1"
  worker.direct_path: True
# List slicer-cli-images to pull and load
slicer-cli-image:
  - dsarchive/histomicstk:latest
  - ghcr.io/girder/girder-volview-dicomrt/worker-volview-dicomrt:latest
worker:
  pip:
    - git+https://github.com/BryonLewis/dive-dsa.git#subdirectory=server
  shell:
    - wget -O ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && mkdir /tmp/ffextracted && tar -xvf ffmpeg.tar.xz -C /tmp/ffextracted --strip-components 1 && cp /tmp/ffextracted/ffmpeg /opt/venv/bin && cp /tmp/ffextracted/ffprobe /opt/venv/bin && rm -rf /tmp/ffextracted
