{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dsa3.secretName" . }}
  labels:
    {{- include "dsa3.labels" . | nindent 4 }}
type: Opaque
stringData:
  girder-admin-password: {{ .Values.credentials.girderAdminPassword | quote }}
  mongodb-root-password: {{ .Values.credentials.mongodbRootPassword | quote }}
  rabbitmq-user: {{ .Values.credentials.rabbitmqUser | quote }}
  rabbitmq-password: {{ .Values.credentials.rabbitmqPassword | quote }}
  celery-broker-url: {{ printf "amqp://%s:%s@%s/" .Values.credentials.rabbitmqUser .Values.credentials.rabbitmqPassword (include "dsa3.rabbitmqHost" .) | quote }}
  celery-result-backend: {{ printf "rpc://%s:%s@%s/" .Values.credentials.rabbitmqUser .Values.credentials.rabbitmqPassword (include "dsa3.rabbitmqHost" .) | quote }}
{{- end }}
