#!/bin/bash
# Start a single-node slurm cluster (munge + slurmctld + slurmd).
# The munge key is baked in at /opt/munge.key by the Dockerfile (it is
# generated by deploy.sh before building) and is also mounted into the worker
# container so both sides share credentials.
set -euxo pipefail

mkdir -p /etc/munge /etc/slurm /run/munge /var/log/munge
cp /opt/munge.key /etc/munge/munge.key
chown munge:munge /etc/munge/munge.key /run/munge /var/log/munge
chmod 600 /etc/munge/munge.key
chmod 711 /etc/munge
chmod 755 /run/munge /var/log/munge

mkdir -p /var/spool/slurmctld /var/spool/slurmd
chown slurm:slurm /var/spool/slurmctld
chown root:root /var/spool/slurmd

runuser -u munge -- munged
sleep 1

# The Ubuntu slurm cgroup/v2 plugin wants to create a systemd-style scope
# directory for slurmstepd.  Create the parent so that it can (the container
# is privileged, so cgroupfs is writable).
mkdir -p /sys/fs/cgroup/system.slice || true

slurmctld
slurmd

echo "==== slurm node ready ===="
sinfo
tail -f /dev/null
